name: Development

on: push

jobs:
  test:
    name: Test whether CVTemplate and all subfiles compile
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/typst/typst:latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "test utils"
        run: typst compile content/utils.typ --root .

      - name: "test CVTemplate"
        run: typst compile test/CVTemplateTest.typ --root .
